version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "America/El_Salvador"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
    groups:
      dev-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "America/El_Salvador"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
